version: '3.3'
services:
  ptp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ptp-backend:latest
    container_name: ptp-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped