version: '3.3'
services:
  ptp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ptp-backend:latest
    container_name: ptp-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped

volumes:
  mongodb-data: